backtest_settings:
  start_date: '2002-01-01'
  end_date: '2024-12-31'
  rebalance_freq: 'M'
  initial_capital: 100.0
  size: 100.0  # Changed to match initial capital for full investment
  size_type: 'value'  # Using value for fixed position size

data:
  file_path: 'data_pipelines/backtest_data.csv'
  target_column: 'cad_ig_er_index'

strategies:
  MA:
    ma_window: 8  # Optimized value based on maximum Sharpe ratio
    entry_threshold: 0.001
  BuyAndHold:
    min_holding_period: 1
  HYTiming:
    ma_window: 5  # Default value, will be optimized
  MRAS:
    regime_ma_window: 60
    regime_vol_window: 20
    momentum_window: 20
    hy_ma_window: 5
    yield_ma_window: 20
    vol_threshold: 0.15
    momentum_threshold: 0.0
    vol_target: 0.10
    max_leverage: 1.0
